- name: add ssh key for shubham
  tags: always
  authorized_key:
    user: shubham
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMMdtY7/E73YRw/VORd1YnqVyQG8/Jfk/sK+HzW3Uv9c ansible"

- name: generate sshd_config file from template
  tags: ssh
  template:
    src: "{{ ssh_template_file }}"
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
  notify: restart_sshd
